INSERT INTO `opensms`.`unit` (`unit`) VALUES ('g');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('kg');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('l');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('ml');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('dozen');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('packet');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('item');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('mg');
INSERT INTO `opensms`.`unit` (`unit`) VALUES ('bottle'); 
